[package]
name = "bevy_ball_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_screen_diagnostics = "0.4.0"
rand = "0.8.5"
